name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devopscourse-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devopscourse-frontend:latest ./frontend

      - name: Push backend image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devopscourse-backend:latest

      - name: Push frontend image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devopscourse-frontend:latest
